### ISSUE TITLE
node_modules\discord-music-player\src\Player.js:379 return this.queues.get(message.guild.id); ^  TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by AshiePleb** [SushiBtw/discord-music-player#126]
Hello, I keep getting the following error.

C:\Users\ashle\Documents\Discord Bots\Sparky Beta\node_modules\discord-music-player\src\Player.js:379
        return this.queues.get(message.guild.id);
                                             ^

TypeError: Cannot read property 'id' of undefined
    at Player.getQueue (C:\Users\ashle\Documents\Discord Bots\Sparky Beta\node_modules\discord-music-player\src\Player.js:379:46)
    at Client.<anonymous> (C:\Users\ashle\Documents\Discord Bots\Sparky Beta\bot.js:154:12)
    at Client.emit (events.js:327:22)
    at MessageCreateAction.handle (C:\Users\ashle\Documents\Discord Bots\Sparky Beta\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\ashle\Documents\Discord Bots\Sparky Beta\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\ashle\Documents\Discord Bots\Sparky Beta\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\ashle\Documents\Discord Bots\Sparky Beta\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\ashle\Documents\Discord Bots\Sparky Beta\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\ashle\Documents\Discord Bots\Sparky Beta\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)

**Comment by SpeckyYT** [comment]
it means that `message.guild` is undefined, which means that the command got executed in a DM.

**Comment by AshiePleb** [comment]
> it means that `message.guild` is undefined, which means that the command got executed in a DM.

But it didn't. I ran it in a server. It seems to work when I use an older version of the module tho.

**Comment by SushiBtw** [comment]
You should pass `message` as first param now, look docs - https://github.com/SushiBtw/discord-music-player#methods

![image](https://user-images.githubusercontent.com/45533122/117290140-ba961b80-ae6d-11eb-8824-09b63f5c6859.png)

**Comment by AshiePleb** [comment]
This is how it's setup (IMG: https://ashleyhunter01.com/ss/4e9ul.png) 

It works fine with version 6.4.0 but with the latest version I get the error I sent above. 

Not to mention I wasn't even running a command that had nothing to do with the music stuff it was a random command my bot has and It gave me that error.

**Comment by SpeckyYT** [comment]
_my god is that some terrible code_

**Comment by AshiePleb** [comment]
> _my god is that some terrible code_

But it should work.. It literally works with a different version of the module but with the latest it doesn't

**Comment by SpeckyYT** [comment]
doesn't `getQueue` require the message item, not an ID?
did you read trough / check the documentation?

**Comment by AshiePleb** [comment]
> doesn't `getQueue` require the message item, not an ID?
> did you read trough / check the documentation?

I did but what I don't understand is why does it work on an older version of the module but not the latest

**Comment by SpeckyYT** [comment]
because it got changed in the newer version.

**Comment by SpeckyYT** [comment]
I guess this issue can be closed now.

**Comment by SushiBtw** [comment]
Nab as per newer versions.
