### ISSUE TITLE
Installation error occurred on my M1 mac 

### ISSUE THREAD

**Issue by limdh0827** [SushiBtw/discord-music-player#194]
node version: v16.9.1
discord.js: 13.1.0 

If I run the command `yarn add discord-music-player` on my device (MacBook Air (M1, 2020)), it will not be installed due to the following errors. →

```
/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.4.1
node-pre-gyp info using node@16.9.1 | darwin | arm64
node-pre-gyp info check checked for "/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-darwin-arm64-unknown-unknown/opus.node" (not found)
node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.5.3/opus-v0.5.3-node-v93-napi-v3-darwin-arm64-unknown-unknown.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.3/opus-v0.5.3-node-v93-napi-v3-darwin-arm64-unknown-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.5.3 and node@16.9.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.3/opus-v0.5.3-node-v93-napi-v3-darwin-arm64-unknown-unknown.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.9.1 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.9.1 | darwin | arm64
gyp info find Python using Python version 3.9.6 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
(node:53632) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/limdohyeop/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/limdohyeop/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/limdohyeop/Library/Caches/node-gyp/16.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/limdohyeop/Library/Caches/node-gyp/16.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/limdohyeop/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/limdohyeop/Library/Caches/node-gyp/16.9.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.9.1 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_projection_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/analysis.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mlp_data.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_projection_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mapping_matrix.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_compare.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mlp.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_decoder.o
In file included from ../deps/opus/src/opus_decoder.c:50:
In file included from ../deps/opus/silk/structs.h:32:
In file included from ../deps/opus/silk/SigProc_FIX.h:51:
../deps/opus/silk/arm/biquad_alt_arm.h:31:11: fatal error: 'celt/arm/armcpu.h' file not found
# include "celt/arm/armcpu.h"
          ^~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/libopus/deps/opus/src/opus_decoder.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/limdohyeop/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/Users/limdohyeop/.nvm/versions/node/v16.9.1/bin/node" "/Users/limdohyeop/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-darwin-arm64-unknown-unknown/opus.node" "--module_name=opus" "--module_path=/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-darwin-arm64-unknown-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus
gyp ERR! node -v v16.9.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/limdohyeop/.nvm/versions/node/v16.9.1/bin/node /Users/limdohyeop/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-darwin-arm64-unknown-unknown/opus.node --module_name=opus --module_path=/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-darwin-arm64-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 21.1.0
node-pre-gyp ERR! command "/Users/limdohyeop/.nvm/versions/node/v16.9.1/bin/node" "/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v16.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.4.1
node-pre-gyp ERR! not ok 
Failed to execute '/Users/limdohyeop/.nvm/versions/node/v16.9.1/bin/node /Users/limdohyeop/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-darwin-arm64-unknown-unknown/opus.node --module_name=opus --module_path=/Volumes/T5/Projects/Discord-Bots/DiscordJS/player/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-darwin-arm64-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)

```
Has anyone experienced the same problem as me?
What should I do if there's a solution? .. Thank you!

**Comment by SushiBtw** [comment]
Seems like a `@discordjs/opus` issue - https://github.com/discordjs/opus/issues/103
