### ISSUE TITLE
[BUG] Error handling crash

### ISSUE THREAD

**Issue by uShifty** [SushiBtw/discord-music-player#200]
**Bug Description**
For some reason randomly when listening to a playlist the bot will crash in result to a 403 error. 

**Reproduction Steps**
Honestly I would say just add a playlist that is some what big and see if it errors out. 

**Expected Result**
I expected it not to crash the bot and if anything skip the song or something.

**Attachments**
```
node:events:385
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Status code: 403')
    at new NodeError (node:internal/errors:371:5)
    at Player.emit (node:events:383:17)
    at FFmpeg.<anonymous> (E:\bot\node_modules\discord-music-player\dist\managers\Queue.js:222:33)
    at FFmpeg.emit (node:events:406:35)
    at PassThrough.<anonymous> (E:\bot\node_modules\discord-ytdl-core\index.js:1:1100)
    at PassThrough.emit (node:events:406:35)
    at PassThrough.emit (node:events:394:28)
    at ClientRequest.<anonymous> (E:\bot\node_modules\miniget\dist\index.js:215:28)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:394:28) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'Status code: 403'
}
```

**Versioning:**
- OS: Windows 19043
- Node Version 16.9.1
- Module Version 8.0.1

**Additional Comments**
I will update to 8.1.0 BUT you claim it fixed error 410 not 403

**Comment by SushiBtw** [comment]
Can you provide the playlist link?

**Comment by SpeckyYT** [comment]
> some what big playlist

Me: \*inputting a 1400+ sons playlist and it works\*

**Comment by uShifty** [comment]
> Can you provide the playlist link?
It happens at random with multiple playlists/albums. Just use anything with over 2 hours worth of songs.
It has happened on a album that I have played once before with no problems. It doesnt always happen but it does randomly happens 

But just because you asked this was one of the playlists: https://www.youtube.com/playlist?list=PLn_ACVlOB7crzRkUt0yfVAQsJsuYNWoJt

**Comment by SushiBtw** [comment]
That's probably due the agae limitations, I will try to avoid it.

**Comment by reikop** [comment]
```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('aborted')
    at new NodeError (node:internal/errors:371:5)
    at Player.emit (node:events:379:17)
    at FFmpeg.<anonymous> (/app/AionDiscordBot/node_modules/discord-music-player/dist/managers/Queue.js:228:33)
    at FFmpeg.emit (node:events:402:35)
    at PassThrough.<anonymous> (/app/AionDiscordBot/node_modules/discord-ytdl-core/index.js:1:1100)
    at PassThrough.emit (node:events:402:35)
    at PassThrough.emit (node:events:402:35)
    at IncomingMessage.onError (/app/AionDiscordBot/node_modules/miniget/dist/index.js:152:24)
    at IncomingMessage.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'aborted'
}
```
I think this error is similar
