### ISSUE TITLE
[BUG] Leave Crash

### ISSUE THREAD

**Issue by xMiniLuke** [SushiBtw/discord-music-player#205]
**Bug Description**

When the bot is not in the channel, and you type for example: ".leave", then the bot instantly crashes

**Reproduction Steps**

This is the .js file i have for the leaving command:

const Command = require("../Structures/Command.js");

module.exports = new Command({
    name: "l",
    description: "Let the bot leave the channel",

    async run(message, args, client) {
        
        let guildQueue = client.player.getQueue(message.guild.id);
        guildQueue.stop();
        message.reply(`\`💠\` The Channel was left`);
        
    }
})

Log tells me following:

TypeError: Cannot read properties of undefined (reading 'stop')
    at Command.run (C:\Users\minil\Desktop\MiniBot\src\Commands\leave.js:10:20)
    at Client.<anonymous> (C:\Users\minil\Desktop\MiniBot\src\index.js:57:13)
    at Client.emit (node:events:394:28)
    at MessageCreateAction.handle (C:\Users\minil\Desktop\MiniBot\node_modules\discord.js\src\client\actions\MessageCreate.js:23:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\minil\Desktop\MiniBot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\minil\Desktop\MiniBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:350:31)
    at WebSocketShard.onPacket (C:\Users\minil\Desktop\MiniBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (C:\Users\minil\Desktop\MiniBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10)
    at WebSocket.onMessage (C:\Users\minil\Desktop\MiniBot\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)

**Additional Comments**
I hope this is enough information. In theory i know that i should implement an if the bot is in the channel, then do this, else just say an text, but im kinda new to  JavaScript so i dont know exactly what to do.

**Comment by SushiBtw** [comment]
Due the guildQueue is undefined.

**Comment by xMiniLuke** [comment]
And what can i do about it?

**Comment by SushiBtw** [comment]
Check by yourself, if the queue exists.
