### ISSUE TITLE
[BUG] Random `Unhandled error. ('Status code: 403')` while playing music

### ISSUE THREAD

**Issue by AranyaMaji** [SushiBtw/discord-music-player#233]
```bash
node:events:381
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Status code: 403')
    at new NodeError (node:internal/errors:371:5)
    at Player.emit (node:events:379:17)
    at FFmpeg.<anonymous> (C:\Users\User\Documents\bot\node_modules\discord-music-player\dist\managers\Queue.js:223:33)
    at FFmpeg.emit (node:events:402:35)
    at PassThrough.<anonymous> (C:\Users\User\Documents\bot\node_modules\discord-ytdl-core\index.js:1:1100)
    at PassThrough.emit (node:events:402:35)
    at PassThrough.emit (node:events:390:28)
    at ClientRequest.<anonymous> (C:\Users\User\Documents\bot\node_modules\miniget\dist\index.js:215:28)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'Status code: 403'
```

**Randomly getting this error while playing music**

- OS: Win 11
- Node Version v16.10.0
- Module Version 8.2.0

**Comment by ka0sdev** [comment]
Let's assume this is while playing music from YouTube, afaik this is not something SushiBtw can do anything about the 403 is thrown from YouTube, and 403 means forbidden.

**Comment by SushiBtw** [comment]
You can handle such errors using such code:
```js
Player#on('error', (queue, err) => {

});
```

**Comment by AranyaMaji** [comment]
> You can handle such errors using such code:
> 
> ```js
> Player#on('error', (queue, err) => {
> 
> });
> ```

yeh im yet to add the on error event 
but will the issue with the error 403 still persist?

**Comment by ka0sdev** [comment]
> > You can handle such errors using such code:
> > ```js
> > Player#on('error', (queue, err) => {
> > 
> > });
> > ```
> 
> yeh im yet to add the on error event but will the issue with the error 403 still persist?

Yes it will, 403 is not something we're remotely able to fix. It's YouTube throwing HTTP 403 which means forbidden, it happens from time to time.

**Comment by MeridianGH** [comment]
Wouldn't it be possible to retry the request a few times on a 403 error?

**Comment by reikop** [comment]
When I repeat the music, the 403 problem does not appear
Is there any difference?
