### ISSUE TITLE
When using Queue#stop() can't request back queue bcs "destroyed"

### ISSUE THREAD

**Issue by Ninja2Gods** [SushiBtw/discord-music-player#235]
When using the method of Queue#stop(), I can't use back the bot until I restart it,

`/home/container/node_modules/discord-music-player/dist/managers/Queue.js:177
                throw new __1.DMPError(__1.DMPErrors.QUEUE_DESTROYED);
                      ^

QueueDestroyed: The Queue was destroyed.
    at Queue.<anonymous> (/home/container/node_modules/discord-music-player/dist/managers/Queue.js:177:23)
    at Generator.next (<anonymous>)
    at /home/container/node_modules/discord-music-player/dist/managers/Queue.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/container/node_modules/discord-music-player/dist/managers/Queue.js:4:12)
    at Queue.play (/home/container/node_modules/discord-music-player/dist/managers/Queue.js:175:16)
    at /home/container/index.js:359:33
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (/home/container/index.js:237:5)`

I'm using the createQueue() method for getting the queue and idk why if I create again the queue, why it's destroyed at the time of creation

**Comment by Night-Hunter-NF** [comment]
let guildQueue = player.getQueue(interaction.guildId); 
use this for getting the queue you only use create queue for the play/playlist function.
