### ISSUE TITLE
[BUG] When you disconnect bot manually, it crashes

### ISSUE THREAD

**Issue by Murtatrxx** [SushiBtw/discord-music-player#255]
**Bug Description**
When you disconnect bot with right click, it is crashing and no longer joining vcs and throwing “The operation was aborted” error

**Reproduction Steps**
1. Right click the bot
2. Disconnect it 
3. Observe the result & error.

**Expected Result**
Should join vcs

**Attachments**
None

**Versioning:**
- OS: Microsoft Windows 11
- Node Version: v16.6.0
- Module Version: v8.3.1

**Additional Comments**
Please fix

**Comment by slienlaffa** [comment]
I tried it, didn't crush but gave the error, and the same error again and again, in intervals of one minute so I had to restart my bot.

**Comment by Murtatrxx** [comment]
Yeah, it’s bugging

**Comment by Murtatrxx** [comment]
So, will it fix?

**Comment by warior456** [comment]
I was kicked from the Voice Channel, queue ended.
node:events:842
      reject(new AbortError());
             ^

AbortError: The operation was aborted
    at abortListener (node:events:842:14)
    at EventTarget.<anonymous> (node:events:878:47)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:559:20)
    at EventTarget.dispatchEvent (node:internal/event_target:504:26)
    at abortSignal (node:internal/abort_controller:97:10)
    at AbortController.abort (node:internal/abort_controller:122:5)
    at Timeout.<anonymous> (H:\discordbot\mrdia-main\node_modules\@discordjs\voice\dist\util\abortAfter.js:10:41)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ABORT_ERR'
}
Restarting Bot..
TypeError: event.bind is not a function
    at load_dir (H:\discordbot\mrdia-main\handlers\event_handler.js:11:45)
    at H:\discordbot\mrdia-main\handlers\event_handler.js:19:38
    at Array.forEach (<anonymous>)
    at module.exports (H:\discordbot\mrdia-main\handlers\event_handler.js:19:25)
    at H:\discordbot\mrdia-main\main.js:62:37
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (H:\discordbot\mrdia-main\main.js:61:55)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
(node:16228) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Mrdia is Online

**Comment by SushiBtw** [comment]
Fix in #249, on npm in few days.
