### ISSUE TITLE
DMPErrors.VOICE_CONNECTION_ERROR

### ISSUE THREAD

**Issue by StrangerGithuber** [SushiBtw/discord-music-player#265]
Hello
When I am trying to play a music then I get an error:
```
C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\discord-music-player@8.3.1\node_modules\discord-music-player\dist\managers\Queue.js:117
                throw new __1.DMPError(__1.DMPErrors.VOICE_CONNECTION_ERROR);
                      ^

DMPError [VoiceConnectionError]: There was an Error while starting the Voice Stream
    at Queue.<anonymous> (C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\discord-music-player@8.3.1\node_modules\discord-music-player\dist\managers\Queue.js:117:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\discord-music-player@8.3.1\node_modules\discord-music-player\dist\managers\Queue.js:6:65)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:497:9)
```

It is my package.json:
```
{
  "name": "client",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "start": "node .",
    "dev": "nodemon .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "devmod": "pm2 start . --watch",
    "stop": "pm2 stop all",
    "devmonit": "pm2 monit"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@discordjs/builders": "^0.9.0",
    "@discordjs/opus": "^0.6.0",
    "@discordjs/rest": "^0.1.0-canary.0",
    "canvas": "^2.8.0",
    "colors": "^1.4.0",
    "common-tags": "^1.8.2",
    "discord-akairo": "github:discord-akairo/discord-akairo",
    "discord-api-types": "^0.25.2",
    "discord-music-player": "^8.3.1",
    "discord.js": "^13.4.0",
    "dotenv": "^10.0.0",
    "fs": "^0.0.1-security",
    "jimp": "^0.16.1",
    "moment": "^2.29.1",
    "mongoose": "^6.1.3",
    "node-fetch": "^2.6.6",
    "nodemon": "^2.0.15",
    "pm2": "^5.1.2",
    "svg-png-converter": "^0.0.9",
    "ytdl-core": "^4.9.2"
  }
}
```

I am using this code: https://github.com/AlexArtaud-Dev/Roomba-V2/blob/main/src/commands/music/play.js

And when I am installing/updating then I get this warning message:
```
 WARN  Issues with peer dependencies found
.
└─┬ discord-music-player
  └─┬ @discordjs/voice
    └─┬ prism-media
      └── ✕ unmet peer @discordjs/opus@^0.5.0: found 0.6.0
.
└─┬ discord-music-player
  └─┬ @discordjs/voice
    └─┬ prism-media
      └── ✕ unmet peer @discordjs/opus@^0.5.0: found 0.6.0
```

What can be the problem? Did I do something wrong?
The bot is joining to the voice channel and it is muted and deafen by default for some reason and couple of seconds later leaving the voice channel and giving the above error message.

**Comment by SushiBtw** [comment]
Are you sure your client has voice intents?
If yes, are you sure it has the permission to join the voice channel?

**Comment by StrangerGithuber** [comment]
Permissions
![image](https://user-images.githubusercontent.com/1939827/147418707-d2b0fced-8a70-47f1-8eb5-ac74196ade70.png)

intents: 32767 which in theory gives all of the intents.

**Comment by Amir-DV** [comment]
maybe use try/catch and it may give the exact error problem

**Comment by StrangerGithuber** [comment]
Hmm well same, if I put in "discord-music-player@8.3.1\node_modules\discord-music-player\dist\managers" folder in the Queue.js file console.log(err) in the line 116 then I get more error:

```
AbortError: The operation was aborted
    at abortListener (node:events:838:14)
    at EventTarget.<anonymous> (node:events:874:47)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at EventTarget.dispatchEvent (node:internal/event_target:504:26)
    at abortSignal (node:internal/abort_controller:97:10)
    at AbortController.abort (node:internal/abort_controller:122:5)
    at Timeout.<anonymous> (C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\@discordjs+voice@0.6.0_b6017d7beb099bb81e43750be7fa0373\node_modules\@discordjs\voice\dist\util\abortAfter.js:10:41)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ABORT_ERR'
}
DMPError [VoiceConnectionError]: There was an Error while starting the Voice Stream
    at Queue.<anonymous> (C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\discord-music-player@8.3.1\node_modules\discord-music-player\dist\managers\Queue.js:118:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\discord-music-player@8.3.1\node_modules\discord-music-player\dist\managers\Queue.js:6:65)
```

**Comment by Amir-DV** [comment]
okay i had the abort_err
while connecting to voice or when queue gets destroyed , u used try/catch?

**Comment by StrangerGithuber** [comment]
This is the code:

```
const { Command } = require('discord-akairo');

class PlayCommand extends Command {
    constructor() {
        super('play', {
            aliases: ['play', 'p'],
            category: 'Music',
            description: {
                content: 'The play command allows you to play music from a search or a URL',
                usage: "play <search>",
                example: ['play Never Gonna give you up', 'play https://www.youtube.com/watch?v=xoWxv2yZXLQ&ab_channel=LeagueofLegends'],
            },
            channel: "guild",
            args: [
                {id: "search", type: 'string', match: "restContent"},
            ],
        });
    }

    async exec(message, { search }) {
        await message.delete();
        try {
        const channel = await this.client.functions.checkMusicChannelExistence(message, message.guild, this.client.guildSettings, this.client);
        console.log('1')
        if (channel.allowed){
            console.log('2')
            let guildQueue = await this.client.musicPlayer.getQueue(message.guild.id);
            console.log('3')
            let queue;
            if (await this.client.functions.checkUserInVoiceChannel(message)){
                console.log('4')
                if (guildQueue){
                    queue = guildQueue;
                }else{
                    console.log('5')
                    queue = await this.client.musicPlayer.createQueue(message.guild.id);
                    console.log('6')
                    await queue.setData({voiceChannelID: message.member.voice.channel.id});
                    console.log('7')
                }
                console.log('8')
                if (await this.client.functions.checkUserInSameVoiceChannelAsBot(message, queue)){
                    console.log('9')
                    let musicEmbed;
                    await queue.join(message.member.voice.channel);
                    console.log('10')
                    const loading = await channel.channelObject.send("Music search ... ");
                    await queue.play(search).then(async data => {
                        console.log('11')
                        setTimeout(() => {
                            if (data){
                                loading.delete();
                                musicEmbed = this.client.functions.musicEmbed(data.name, data.url, data.duration, data.isLive, data.thumbnail, message.author, this.client.colors.color.darkpurple, queue.songs.length)
                                channel.channelObject.send({ embeds : [musicEmbed]})
                            }else{
                                loading.delete();
                                channel.channelObject.send("No music was found!")
                            }
                        },2000)
                        console.log('12')
                    await this.client.log.music.logCommand(message.guildId, message.author, this.id, {search: search});
                    console.log('3')
                    }).catch(error => {
                        console.log(error)
                        this.client.log.music.error(message.guildId, error.message);
                        channel.channelObject.send(error.message);
                    })
                }
            }
        }
    } catch (err){
        console.log(err)
    }

    }
}
module.exports = PlayCommand;
```

I put many console.log to check where stuck. Otherwise I used try/catch but I get only the above message.
When using the play command then it stuck on 9 and can't go to 10. Which means something is problem with `await queue.join(message.member.voice.channel);`.

**Comment by SpeckyYT** [comment]
that means the bot doesn't have the permissions to join that voice channel

**Comment by StrangerGithuber** [comment]
I have these permissions as default for the bot when someone is inviting it:
```
const PERMISSIONS = [
    'CONNECT',
    'SPEAK',
    'USE_VAD',
    'MANAGE_MESSAGES',
    'SEND_MESSAGES',
    'SEND_TTS_MESSAGES',
    'ATTACH_FILES',
    'USE_EXTERNAL_EMOJIS',
    'CHANGE_NICKNAME',
    'MANAGE_NICKNAMES',
    'MANAGE_ROLES',
    'MANAGE_THREADS',
    'CREATE_PUBLIC_THREADS',
    'USE_EXTERNAL_STICKERS',
    'SEND_MESSAGES_IN_THREADS',
    'START_EMBEDDED_ACTIVITIES',
    'EMBED_LINKS',
    'READ_MESSAGE_HISTORY',
    'USE_PUBLIC_THREADS',
    'USE_PRIVATE_THREADS',
    'MANAGE_CHANNELS',
    'MANAGE_GUILD',
    'ADD_REACTIONS',
    'VIEW_AUDIT_LOG',
    'BAN_MEMBERS',
    'KICK_MEMBERS',
    'CREATE_INSTANT_INVITE',
    'VIEW_CHANNEL'
];
```

I tried not long time ago just with administration permission. I mean inviting the bot with admin permission and the result is the same. Hmm it means if for others works this and just for me not working then maybe my computer has problem with streaming. or I don't know.

**Comment by StrangerGithuber** [comment]
Well I will close this because no idea what can be the problem. Thank you for everybody who tried to help. You are the best. :)
