### ISSUE TITLE
[BUG] Short bug description

### ISSUE THREAD

**Issue by Ninja2Gods** [SushiBtw/discord-music-player#309]
Undefined `connection` throwing error:

```
/home/container/node_modules/discord-music-player/dist/managers/Queue.js:197
            throw new __1.DMPError(__1.DMPErrors.NO_VOICE_CONNECTION);
                  ^
NoVoiceConnection: There is no Queue#connection [you should use Queue#join()] first.
    at Queue.play (/home/container/node_modules/discord-music-player/dist/managers/Queue.js:197:19)
    at Object.run (/home/container/comandos/music/play.js:33:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

And code is:

```
const Discord = require("discord.js");
const { Player } = require("discord-player");

module.exports = {
    
    data: new Discord.SlashCommandBuilder()
    .setName("play")
    .setDescription("▶ | Pon a reproducir una canción")
    .addStringOption(options => 
        options.setName("canción")
        .setDescription("🎧 | Especifica la canción a reproducir")
        .setRequired(true)
    ),
    run: async (client, interaction) => {
        
        const song = interaction.options.getString("canción");
        
        if(!interaction.member.voice.channelId) {
            
            const embed = new Discord.EmbedBuilder()
            	.setTitle("🔌 | No estás conectado a un canal de voz!")
            	.setColor(client.color)
            	.setDescription("> No puedo entrar a reproducir música sin ti!")
            
            return interaction.reply({ embeds: [embed] , ephemeral : true })
            
        }
        
        let queue = await client.player.createQueue(interaction.guild.id);
        
        if(!queue.connection) queue.join(interaction.member.voice.channelId);
        
        queue.play(song)
    }
    
}

```

**Comment by securing-ab** [comment]
id consider trying:         `if(!queue.connection) queue.join(interaction.member.voice.channel);`

**Comment by Ninja2Gods** [comment]
> id consider trying: `if(!queue.connection) queue.join(interaction.member.voice.channel);`

Literally that's the problem, that after joining, `queue.connection`  it's undefined
