### ISSUE TITLE
[BUG] in downloading the package

### ISSUE THREAD

**Issue by HeemPlayz** [SushiBtw/discord-music-player#31]
**Bug Description**
Installing a new package will give an error
which is:
``` 
       if (voiceChannel?.type !== 'voice' ?? true) return new MusicPlayerError('VoiceChannelTypeInvalid', 'song');
                         ^
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/rbd/pnpm-volume/6a1aec51-3af4-4d70-b296-052c755d830a/node_modules/.registry.npmjs.org/discord-music-player/6.3.1/node_modules/discord-music-player/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)```

**Reproduction Steps**
Steps to reproduce the behavior:
1. download the packages
2. monitor

**Comment by SushiBtw** [comment]
Please update your node version to 14 or higher.

**Comment by HeemPlayz** [comment]
Thanks, issue resolved
