### ISSUE TITLE
[BUG] Error in display_name property when loading a playlist

### ISSUE THREAD

**Issue by Cundalf** [SushiBtw/discord-music-player#316]
**Bug Description**
Since a few days I can not play a playlist. It doesn't matter if it's from youtube or spotify. I haven't changed any of my code lately.

My code:
          
```
await queue.join(guildMember.voice.channel as VoiceBasedChannel);

// const playlistInQueue =
await queue.playlist(playlist)
    .catch(err => {
        console.log(err);
        if (!guildQueue) {
            queue.stop();
        }
    });
```

**Error**

```
TypeError: Cannot read properties of undefined (reading 'display_name'): There was an Unknown Error.
    at ...\node_modules\discord-music-player\dist\managers\Queue.js:271:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Queue.playlist (...\node_modules\discord-music-player\dist\managers\Queue.js:269:24) 
    at async PlaylistCommand.execute (...\src\commands\musicCommands\playlist.ts:24:17)
```

**Versioning:**
- OS: Docker Image 16-alpine.
- Node Version 16.17.0
- Discord.js version 14.3.0
- Discord.js opus version 0.8.0
- Discord.js voice version 0.11.0

**Comment by ExQDev** [comment]
The same

**Comment by SushiBtw** [comment]
Will check

**Comment by Klairm** [comment]
Same, but only happens to me with spotify playlists, yt lists works good
