### ISSUE TITLE
[BUG] I can't play certain youtube links

### ISSUE THREAD

**Issue by Alexmdz77** [SushiBtw/discord-music-player#63]
**Bug Description**
When I play certain youtube videos, the bot joins the voice channel but doesn't play any video and instantly leaves the channel.

I think he was leaving because the timeout is 0 by default, by increasing it, I get an error : 
```
TypeError: Cannot read property 'url' of undefined
at Player._playSong (/node_modules/discord-music-player/src/Player.js:541:34)
at StreamDispatcher.<anonymous> (/node_modules/discord-music-player/src/Player.js:563:29)
at StreamDispatcher.emit (events.js:326:22)
at finishMaybe (_stream_writable.js:639:14)
at _stream_writable.js:616:5
at StreamDispatcher._final (/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:248:5)
at callFinal (_stream_writable.js:609:10)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Reproduction Steps**
The links used : https://youtu.be/C_29TAVQrm8 and https://www.youtube.com/watch?v=VOxtCodiqPU
The code of the play command : 
```
let isPlaying = client.player.isPlaying(message.guild.id);
    // If there's already a song playing
    if(isPlaying){
        // Add the song to the queue
        let song = await client.player.addToQueue(message.guild.id, args.join(' '), {}, message.author.tag);
        song = song.song;

        message.channel.send(`Song ${song.name} was added to the queue!`);
    } else {
        // Else, play the song
        let song = await client.player.play(message.member.voice.channel, args.join(' '), {}, message.author.tag).then(async song => {
            if(song.error) throw(song.error);
            song = song.song;
            message.channel.send(`Started playing ${song.name}.`);
        }).catch(err => {
            console.log(err);
        });
```
I don't know what additional information you need, ask me if you want more.

**Versioning:**
- OS : Debian GNU/Linux 9.13
- NPM Version v7.5.2
- discord.js v12.5.1
- ytdl-core v4.4.5
- discord-music-player v6.4.1

**Comment by SushiBtw** [comment]
Are you still able to reproduce the issue? It seems' that I can't reproduce it.

**Comment by SushiBtw** [comment]
I will add a catch method for it, if it still happens for you.

**Comment by Alexmdz77** [comment]
The problem is still there, I've seen that it could be due to Youtube restrictions but I'm not sure about that.

**Comment by SushiBtw** [comment]
Okay, can you please try running this code?
```js
const { Utils } = require('discord-music-player');
let SongResult = await Utils.getVideoBySearch(`TheLinkGoesHere`, {}, null, null)

console.log(SongResult);
```
Can you send me the Log that it prints?

**Comment by Alexmdz77** [comment]
The result looks correct
![image](https://user-images.githubusercontent.com/32090268/106870475-74e08000-66d1-11eb-86ff-e1eb07dc810a.png)

I didn't specify but the message 'Started playing ${song.name}' is displayed correctly too.

**Comment by SushiBtw** [comment]
So, when you could reproduce the issue, you added the 2nd song to the queue?

**Comment by Alexmdz77** [comment]
The bot joins the channel, the message is sent but the song is not in the queue and it doesn't play.

**Comment by SushiBtw** [comment]
```js
        let song = await client.player.play(message.member.voice.channel, args.join(' '), {}, message.author.tag).then(async song => {
            if(song.error) throw(song.error);
           console.log(song);
            song = song.song;
            message.channel.send(`Started playing ${song.name}.`);
        }).catch(err => {
            console.log(err);
        });
        ```
Can you send me the result?

**Comment by Alexmdz77** [comment]
```
3|app  | {
3|app  |   error: null,
3|app  |   song: Song {
3|app  |     name: 'Maes - Dybala ft. Jul',
3|app  |     duration: '3:30',
3|app  |     author: 'Maes officiel',
3|app  |     url: 'https://www.youtube.com/watch?v=VOxtCodiqPU',
3|app  |     thumbnail: 'https://i.ytimg.com/vi/VOxtCodiqPU/maxresdefault.jpg',
3|app  |     queue: Queue {
3|app  |       _events: [Object: null prototype] {},
3|app  |       _eventsCount: 0,
3|app  |       _maxListeners: undefined,
3|app  |       guildID: '567037793952464916',
3|app  |       dispatcher: null,
3|app  |       connection: [VoiceConnection],
3|app  |       songs: [Array],
3|app  |       stopped: false,
3|app  |       skipped: false,
3|app  |       volume: 100,
3|app  |       playing: true,
3|app  |       repeatMode: false,
3|app  |       repeatQueue: false,
3|app  |       [Symbol(kCapture)]: false
3|app  |     },
3|app  |     requestedBy: 'Alexmdz77#2262',
3|app  |     seekTime: 0
3|app  |   }
3|app  | }
```

**Comment by SushiBtw** [comment]
and can you console the ``song.queue.songs``?

**Comment by Alexmdz77** [comment]
```
TypeError: Cannot read property 'songs' of undefined
3|app  |     at /bot/Commandes/music/play.js:63:35
3|app  |     at runMicrotasks (<anonymous>)
3|app  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
3|app  |     at async Object.module.exports.run (/bot/Commandes/music/play.js:60:20)
```

**Comment by SushiBtw** [comment]
console log it after ``song = song.song;`` please.

**Comment by Alexmdz77** [comment]
Oh I just saw it sorry
```
3|app  | [
3|app  |   Song {
3|app  |     name: 'Maes - Dybala ft. Jul',
3|app  |     duration: '3:30',
3|app  |     author: 'Maes officiel',
3|app  |     url: 'https://www.youtube.com/watch?v=VOxtCodiqPU',
3|app  |     thumbnail: 'https://i.ytimg.com/vi/VOxtCodiqPU/maxresdefault.jpg',
3|app  |     queue: Queue {
3|app  |       _events: [Object: null prototype] {},
3|app  |       _eventsCount: 0,
3|app  |       _maxListeners: undefined,
3|app  |       guildID: '567037793952464916',
3|app  |       dispatcher: null,
3|app  |       connection: [VoiceConnection],
3|app  |       songs: [Circular],
3|app  |       stopped: false,
3|app  |       skipped: false,
3|app  |       volume: 100,
3|app  |       playing: true,
3|app  |       repeatMode: false,
3|app  |       repeatQueue: false,
3|app  |       [Symbol(kCapture)]: false
3|app  |     },
3|app  |     requestedBy: 'Alexmdz77#2262',
3|app  |     seekTime: 0
3|app  |   }
3|app  | ]
```
This all looks good, I think it's a error with ytdl-core maybe?

**Comment by SushiBtw** [comment]
Huuh, seems that everything should work fine - I will look into it.

**Comment by Alexmdz77** [comment]
Ok, It's not an error with your module, it must be some restrictions on certain videos yt, locally or on another machine it works very well, I'll try to fix it on my machine. I don't bother you more, thanks !
