### ISSUE TITLE
[BUG] URL undefined during stop()

### ISSUE THREAD

**Issue by EvasiveXkiller** [SushiBtw/discord-music-player#70]
**Bug Description**
The bug occurs sometimes when the stop() function is called

**Reproduction Steps**
By observation this bug occurs when stop is called when there is no queue. If the song is played from queue it seems to be fine

**Expected Result**
No Errors

**Attachments**
Console Output
```
(node:1860) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at Player._playSong (E:\github\bot\node_modules\discord-music-player\src\Player.js:541:34)
    at StreamDispatcher.<anonymous> (E:\github\bot\node_modules\discord-music-player\src\Player.js:563:29)
    at StreamDispatcher.emit (events.js:327:22)
    at finish (_stream_writable.js:657:10)
    at finishMaybe (_stream_writable.js:644:9)
    at _stream_writable.js:617:7
    at StreamDispatcher._final (E:\github\bot\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:248:5)
    at callFinal (_stream_writable.js:610:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SushiBtw** [comment]
Hey, seems some Users keeps getting those errors, I am going to look into this issue.
#69

**Comment by SushiBtw** [comment]
I will be working on this issue.
